# This is a basic workflow to help you get started with Actions

name: Example Workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "Hello from LASP!"
          echo "So Long!"

  build2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello Again from LASP!"
          echo "So Long Again!"
  
